imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_host%"
            options:
                readPreference: primaryPreferred
                connectTimeoutMS: 10000
    default_database: blog_test
    document_managers:
        default:
            auto_mapping: true